# Generated by Django 5.1.2 on 2024-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='parent_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
