# Generated by Django 5.1.2 on 2024-10-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='order_number',
            new_name='invoice_no',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transportation_fee',
            new_name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cart_id',
        ),
    ]
