# Generated by Django 5.1.2 on 2024-10-25 03:05

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_order_number_purchase_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
