# Generated by Django 5.1.2 on 2024-10-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchaseproduct_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_products', to='purchase.purchase'),
        ),
    ]
