# Generated by Django 5.1.2 on 2024-10-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchase_status'),
        ('store', '0004_unit_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_products', to='store.product'),
        ),
    ]
