# Generated by Django 5.1.2 on 2024-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='delivery_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
