# Generated by Django 4.0 on 2024-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentmethod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(default='deli', max_length=20, verbose_name=(('deli', 'Delivery'), ('col', 'Self Collect'))),
        ),
    ]
